### ISSUE TITLE
Lower time interval than a day

### ISSUE THREAD

**Issue by seb128** [powersj/ubuntu-bug-triage#15]
Currently there is a required int number of days argument

The triage class does
        self.date = (datetime.now().date() - timedelta(days=days)).strftime("%Y-%m-%d")

It means if you do a round on triaging on monday afternoon and one on tuesday morning, the tuesday one is going to give you a stack of monday bugs you already saw.

Would you be open to have changed in some way? I'm happy to propose code changes but was not sure what the best approach would be...

* add triage_start option argument that overtake the int day default one if specified? (that would maintain compat but be a bit weird)
* change the current argument to be something else then a day? (would make the simple case less simple though)
* other?

Ideally it would either allow specifying a time (2020-08-10T10:30), or a number of hours would probably be good enough.

Also would it make sense to change the 1 day computation to be from the same time yesterday rather than from the start of the day? (so people doing a daily triage at a fixed time e.G start of work day wouldn't get already reviewed items)

**Comment by powersj** [comment]
The server team uses a cron job/jenkins job that would email the team at the same time every day with the list of bugs to triage. That way it was always generated at the same time, everyone knew what needed to be looked at, and it gave us an easy way to respond to the team if there were questions about a particular bug.

One of our key goals was to triage every single bug that comes in. When we started doing triage it was our fear that we would miss bugs if we made the time element too small. Since we rotated on days having the filter set to days made sense.

When you do see overlap is it usually with newer bugs, those filed on the day you are doing triage?

**Comment by powersj** [comment]
I ask my last question since when we query Launchpad we use the `modified_since=self.date,` to filter on. This means that bugs from today may show up in both your query today and tomorrow. One thing we could do is filter out the current day's bugs?

**Comment by seb128** [comment]
> When you do see overlap is it usually with newer bugs, those filed on the day you are doing triage?

Well, as mentioned your code does

`        self.date = (datetime.now().date() - timedelta(days=days)).strftime("%Y-%m-%dT")`

So if I try now at 10am UTC I get '2020-08-13' which is the value you then use in

```
        """Print update bugs for a specific date or date range."""
        updated_tasks = self.launchpad.distributions["Ubuntu"].searchTasks(
            modified_since=self.date,
```
Which means you get all the bugs modified since yesterday midnight. It works if you generate your report at midnight, but if you do at e.g 7am then you would get the past 24 hours + the bugs modified the previous days before 0am and 7am again (which you already had in your report the previous day) right?

Changing the code to be
`        self.date = (datetime.now() - timedelta(days=days)).strftime("%Y-%m-%dT%H:%M")`

would fix that issue

Still doing that change wouldn't fix the case of a bug triager who manually use the tool to do a triaging round monday at 7am and then another one tuesday a 6pm and would like to review the bugs that changed in between those

**Comment by seb128** [comment]
Thanks for fixing the logic, it doesn't address the request for a lower interval and the usecase described in the previous comment though ... do you want another report about that specific request or do you consider it as a wontfix?

**Comment by powersj** [comment]
@seb128 thanks for your patience! I have pushed the change. If you could let me know if this works better for you I would appreciate it! I released snap rev 215. with this and the new `--urls` option.

Can you file another bug for the additional request and I can try tackling that one soon.
