### ISSUE TITLE
New argument to print the list of URL on stdout?

### ISSUE THREAD

**Issue by seb128** [powersj/ubuntu-bug-triage#16]
Currently the script iterate over all the bugs to review and open them one by one with a sleep delay between each items. The issue is that the webbrowser takes the focus each time an URL is open, which basically DoS the desktop while processing (desktop set can easily go over 30 bugs on a daily view, which means after a weekend you get a machine you can't use for several minutes).

It doesn't seem to be possible to easily open the list of URL in one call from the snap, would it be an acceptable alternative to you to add an option to print the list of URL on stdout?

That way one could call the script with e.g --printurls | xargs webbrowser and avoid the issue

**Comment by powersj** [comment]
Thanks for the issue and for taking the time to think through this! I remember trying to find an elegant way to open the issues in a browser from the snap and as you discovered the current method is a really poor experience.

I like your proposal with the print urls option. Would the following work:

```
$ ubuntu-bug-triage --urls
https://bugs.launchpad.net/bugs/1891331
https://bugs.launchpad.net/bugs/1891331
https://bugs.launchpad.net/bugs/1891552
```

**Comment by powersj** [comment]
See #17 as a fix
